import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/UI/Common/Navbar";
import Footer from "@/components/UI/Common/Footer";
import { Web3Provider } from "@/components/Providers/web3Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3Provider>
          <div className="max-w-[1400px] mx-auto px-4">
            <Navbar />
            <div className="fit">
              {children}
            </div>
          </div>
          <div className="w-full">
            <Footer />
          </div>
        </Web3Provider>
      </body>
    </html>
  );
}
